# kubectl patch deployment argo-server --type JSON --patch-file k8s/argo-server-patch.yaml
- op: replace
  path: "/spec/template/spec/containers/0/args"
  value: 
    - server
    - --auth-mode=server
    - --secure=false
- op: replace
  path: "/spec/template/spec/containers/0/readinessProbe/httpGet/scheme"
  value: HTTP
